// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.FileNesting
{
    static class Vsix
    {
        public const string Id = "6c799bc4-0d4c-4172-98bc-5d464b612dca";
        public const string Name = "File Nesting";
        public const string Description = "Automatically nest files based on file name and enables developers to nest and unnest any file manually";
        public const string Language = "en-US";
        public const string Version = "2.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "file, nesting, solution explorer";
    }
}
